# Site settings
timezone: Europe/Berlin

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://cy-bai.github.io/" # the base hostname & protocol for your site

title: Home #Interactive Graphics Engineer
author: Chongyang Bai(拜重阳)
portrait: "/img/cybai.jpg"

flickr_user: "131006004@N06"
flickr_api_key: adb4be93419edab991522b4fa92b7029

description: > # this means to ignore newlines until "baseurl:"
     Undergraduate in Mathematics, University of Science and Technology of China (USTC).
subheading: > # this means to ignore newlines until "baseurl:"
    Undergraduate in Mathematics,  <a href="http://ustc.edu.cn" target="_blank">University of Science and Technology of China</a>(USTC). <br><br>Interested in Computer Graphics, Computer Vision and Machine Learning.

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown
